- name: Check if a user exists in Azure AD
  hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: Get user details
      azure.azcollection.azure_ad_user_info:
        client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
        secret: "{{ lookup('env', 'AZURE_CLIENT_SECRET') }}"
        tenant: "{{ lookup('env', 'AZURE_TENANT_ID') }}"
        object_id: "user@example.com"
      register: user_info

    - debug:
        var: user_info
