- name: Manage Azure AD Users
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Check if user exists
      shell: python3 Azure_Python.py check_user '{{ "Abhishek.U@amitomar63gmail.onmicrosoft.com" }}'
      register: user_exists

  
