- name: Manage Azure AD Users
  hosts: localhost
  gather_facts: no
  tasks:

    - name: Authenticate with Azure AD
      shell: az login --service-principal -u "{{ client_id }}" -p "{{ client_secret }}" --tenant "{{ tenant_id }}"
      register: auth_result

    - name: Display login result
      debug:
        var: auth_result.stdout_lines

    - name: Check if user exists
      shell: az ad user show --id "{{ user_principal_name }}" --query "id" --output tsv
      register: user_check
      ignore_errors: yes

    - name: Display user check result
      debug:
        var: user_check.stdout
