---
- hosts: all
  collections:
    - community.windows
- name: Check if a user exists in Azure AD
  hosts: localhost
  connection: local
  tasks:
    - name: Get user details
        client_id: "{{ client_id }}"
        secret: "{{ secret') }}"
        tenant: "{{ tenant }}"
        object_id: "user@example.com"
      register: user_info

    - debug:
        var: user_info

